title: Oliver Baldwin Edwards # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  
  
  <a href="https://github.com/Oliver-BE" target="_blank">View My GitHub Profile</a> 
  <a href="https://www.linkedin.com/in/example/" target="_blank">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
