title: Oliver Baldwin Edwards # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hi! My name is Oliver and I'm a senior at <strong>Amherst College</strong> double majoring in <strong>Computer Science</strong> and <strong>Statistics</strong>.
  I’m originally from Evanston, Illinois but recently moved to New Orleans.
  I'm especially interested in  <strong>interactive data visualizations</strong> and  <strong>evolutionary computation</strong>.
  Outside of that, I enjoy photography, playing the piano, and rock climbing.
  <hr> 

  <a href="www.linkedin.com/in/oliver-baldwin-edwards">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-180546121-1 # your Google Analytics tracking ID here
