url: https://oliver-be.ml
baseurl: 
title: Oliver Baldwin Edwards # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: "Oliver Baldwin Edwards' portfolio website."
bio: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hi! My name is Oliver and I'm a Software Engineer at <a href="https://sig-gis.com/" target="_blank">Spatial Informatics Group</a>.
  I'm a recent graduate of <strong>Amherst College</strong> where I double majored in <strong>Computer Science</strong> and <strong>Statistics</strong>.
  I'm especially interested in <strong>evolutionary computation</strong>, <strong>machine learning</strong>, and <strong>natural language processing</strong>.
  Outside of that, I enjoy photography, playing the piano, and rock climbing.
  <br>
  <br>
  <a target="_blank" href="https://linkedin.com/in/oliver-baldwin-edwards">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-180546121-1 # your Google Analytics tracking ID here
