title: Oliver Baldwin Edwards # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hi! My name is Oliver and I'm a senior at <strong>Amherst College</strong> double majoring in Computer Science and Statistics.
  I’m originally from Evanston, Illinois but recently moved to New Orleans.
  I'm especially interested in interactive data visualizations and evolutionary computation.
  Outside of that, I enjoy photography, playing the piano, and rock climbing.
  <hr> 
  
theme: jekyll-theme-minimal
google_analytics: UA-180546121-1 # your Google Analytics tracking ID here
