title: Oliver Baldwin Edwards # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! My name’s Oliver and I'm a senior Computer Science and Statistics double major. 
  I’m originally from Evanston, Illinois but recently moved to New Orleans.
  I'm especially interested in evolutionary computation and interactive data visualizations. 
  Outside of that, I enjoy photography, playing the piano, and rock climbing.
  <hr>

  <a href="https://github.com/Oliver-BE">View My GitHub Profile</a> 
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-180546121-1 # your Google Analytics tracking ID here
